
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author matin
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    String text = "---";
    String textx = "xxx";
    String texto = "ooo";
    boolean x = true;
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reset = new javax.swing.JButton();
        start = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        x1 = new javax.swing.JButton();
        x3 = new javax.swing.JButton();
        x2 = new javax.swing.JButton();
        x4 = new javax.swing.JButton();
        x6 = new javax.swing.JButton();
        x5 = new javax.swing.JButton();
        x9 = new javax.swing.JButton();
        x8 = new javax.swing.JButton();
        x7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        turn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        reset.setText("Reset");
        reset.setEnabled(false);
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        start.setText("Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        x1.setText("---");
        x1.setEnabled(false);
        x1.setMaximumSize(new java.awt.Dimension(45, 45));
        x1.setMinimumSize(new java.awt.Dimension(45, 45));
        x1.setPreferredSize(new java.awt.Dimension(45, 45));
        x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x1ActionPerformed(evt);
            }
        });

        x3.setText("---");
        x3.setEnabled(false);
        x3.setMaximumSize(new java.awt.Dimension(45, 45));
        x3.setMinimumSize(new java.awt.Dimension(45, 45));
        x3.setPreferredSize(new java.awt.Dimension(45, 45));
        x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x3ActionPerformed(evt);
            }
        });

        x2.setText("---");
        x2.setEnabled(false);
        x2.setMaximumSize(new java.awt.Dimension(45, 45));
        x2.setMinimumSize(new java.awt.Dimension(45, 45));
        x2.setPreferredSize(new java.awt.Dimension(45, 45));
        x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x2ActionPerformed(evt);
            }
        });

        x4.setText("---");
        x4.setEnabled(false);
        x4.setMaximumSize(new java.awt.Dimension(45, 45));
        x4.setMinimumSize(new java.awt.Dimension(45, 45));
        x4.setPreferredSize(new java.awt.Dimension(45, 45));
        x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x4ActionPerformed(evt);
            }
        });

        x6.setText("---");
        x6.setEnabled(false);
        x6.setMaximumSize(new java.awt.Dimension(45, 45));
        x6.setMinimumSize(new java.awt.Dimension(45, 45));
        x6.setPreferredSize(new java.awt.Dimension(45, 45));
        x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x6ActionPerformed(evt);
            }
        });

        x5.setText("---");
        x5.setEnabled(false);
        x5.setMaximumSize(new java.awt.Dimension(45, 45));
        x5.setMinimumSize(new java.awt.Dimension(45, 45));
        x5.setPreferredSize(new java.awt.Dimension(45, 45));
        x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x5ActionPerformed(evt);
            }
        });

        x9.setText("---");
        x9.setEnabled(false);
        x9.setMaximumSize(new java.awt.Dimension(45, 45));
        x9.setMinimumSize(new java.awt.Dimension(45, 45));
        x9.setPreferredSize(new java.awt.Dimension(45, 45));
        x9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x9ActionPerformed(evt);
            }
        });

        x8.setText("---");
        x8.setEnabled(false);
        x8.setMaximumSize(new java.awt.Dimension(45, 45));
        x8.setMinimumSize(new java.awt.Dimension(45, 45));
        x8.setPreferredSize(new java.awt.Dimension(45, 45));
        x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x8ActionPerformed(evt);
            }
        });

        x7.setText("---");
        x7.setEnabled(false);
        x7.setMaximumSize(new java.awt.Dimension(45, 45));
        x7.setMinimumSize(new java.awt.Dimension(45, 45));
        x7.setPreferredSize(new java.awt.Dimension(45, 45));
        x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x7ActionPerformed(evt);
            }
        });

        jLabel1.setText("Human");

        jLabel2.setText("Human");

        jLabel3.setText("Vs.");

        turn.setText("Game starts with User 1 (X)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1)
                            .addGap(73, 73, 73)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(start)
                            .addGap(27, 27, 27)
                            .addComponent(reset)
                            .addGap(36, 36, 36)
                            .addComponent(exit))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(x6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(x7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(x8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(x9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(turn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(turn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset)
                    .addComponent(start)
                    .addComponent(exit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        start();
        reset.setEnabled(true);
    }//GEN-LAST:event_startActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        reset();
        start.setEnabled(true);
    }//GEN-LAST:event_resetActionPerformed

    private void x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x1ActionPerformed
        // TODO add your handling code here:
        if (check()) {
            x1.setText(textx);
        }
        else{
            x1.setText(texto);
        }
        x1.setEnabled(false);
        checkgame();
    }//GEN-LAST:event_x1ActionPerformed

    private void x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x2ActionPerformed
        // TODO add your handling code here:
        if (check()) {
            x2.setText(textx);
        }
        else{
            x2.setText(texto);
        }
        x2.setEnabled(false);
        checkgame();        
    }//GEN-LAST:event_x2ActionPerformed

    private void x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x3ActionPerformed
        // TODO add your handling code here:
        if (check()) {
            x3.setText(textx);
        }
        else{
            x3.setText(texto);
        }
        x3.setEnabled(false);
        checkgame();
    }//GEN-LAST:event_x3ActionPerformed

    private void x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x4ActionPerformed
        // TODO add your handling code here:
        if (check()) {
            x4.setText(textx);
        }
        else{
            x4.setText(texto);
        }
        x4.setEnabled(false);
        checkgame(); 
    }//GEN-LAST:event_x4ActionPerformed

    private void x5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x5ActionPerformed
        // TODO add your handling code here:
        if (check()) {
            x5.setText(textx);
        }
        else{
            x5.setText(texto);
        }
        x5.setEnabled(false);
        checkgame(); 
    }//GEN-LAST:event_x5ActionPerformed

    private void x6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x6ActionPerformed
        // TODO add your handling code here:
        if (check()) {
            x6.setText(textx);
        }
        else{
            x6.setText(texto);
        }
        x6.setEnabled(false);
        checkgame(); 
    }//GEN-LAST:event_x6ActionPerformed

    private void x7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x7ActionPerformed
        // TODO add your handling code here:
        if (check()) {
            x7.setText(textx);
        }
        else{
            x7.setText(texto);
        }
        x7.setEnabled(false);
        checkgame(); 
    }//GEN-LAST:event_x7ActionPerformed

    private void x8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x8ActionPerformed
        // TODO add your handling code here:
        if (check()) {
            x8.setText(textx);
        }
        else{
            x8.setText(texto);
        }
        x8.setEnabled(false);
        checkgame(); 
    }//GEN-LAST:event_x8ActionPerformed

    private void x9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x9ActionPerformed
        // TODO add your handling code here:
        if (check()) {
            x9.setText(textx);
        }
        else{
            x9.setText(texto);
        }
        x9.setEnabled(false);
        checkgame(); 
    }//GEN-LAST:event_x9ActionPerformed
    public boolean check(){
        if (x) {
            x = !x;
            turn.setText("User 2's turn (O)");
            return true;
        }
        else{
            x = !x;
            turn.setText("User 1's turn (x)");
            return false;
        }    
    }
    public void checkgame(){
        if (x1.getText().equals(x2.getText()) && x1.getText().equals(x3.getText()) && !x1.getText().equals(text)) {
            if (x1.getText().equals(textx)) {
                JOptionPane.showMessageDialog(rootPane, "User 1 is the winner !!");
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "User 2 is the winner !!");
            }
            gamedone();
        }
        else if (x4.getText().equals(x5.getText()) && x4.getText().equals(x6.getText()) && !x4.getText().equals(text) ) {
            if (x4.getText().equals(textx)) {
                JOptionPane.showMessageDialog(rootPane, "User 1 is the winner !!");
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "User 2 is the winner !!");
            }
            gamedone();
        }
        else if (x7.getText().equals(x8.getText()) && x7.getText().equals(x9.getText()) && !x7.getText().equals(text) ) {
            if (x7.getText().equals(textx)) {
                JOptionPane.showMessageDialog(rootPane, "User 1 is the winner !!");
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "User 2 is the winner !!");
            }
            gamedone();
        }
        else if (x1.getText().equals(x4.getText()) && x1.getText().equals(x7.getText()) && !x1.getText().equals(text) ) {
            if (x1.getText().equals(textx)) {
                JOptionPane.showMessageDialog(rootPane, "User 1 is the winner !!");
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "User 2 is the winner !!");
            }
            gamedone();
        }
        else if (x2.getText().equals(x5.getText()) && x2.getText().equals(x8.getText()) && !x2.getText().equals(text) ) {
            if (x2.getText().equals(textx)) {
                JOptionPane.showMessageDialog(rootPane, "User 1 is the winner !!");
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "User 2 is the winner !!");
            }
            gamedone();
        }
        else if (x3.getText().equals(x6.getText()) && x3.getText().equals(x9.getText()) && !x3.getText().equals(text) ) {
            if (x3.getText().equals(textx)) {
                JOptionPane.showMessageDialog(rootPane, "User 1 is the winner !!");
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "User 2 is the winner !!");
            }
            gamedone();
        }
        else if (x1.getText().equals(x5.getText()) && x1.getText().equals(x9.getText()) && !x1.getText().equals(text) ) {
            if (x1.getText().equals(textx)) {
                JOptionPane.showMessageDialog(rootPane, "User 1 is the winner !!");
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "User 2 is the winner !!");
            }
            gamedone();
        }
        else if (x3.getText().equals(x5.getText()) && x3.getText().equals(x7.getText()) && !x3.getText().equals(text) ) {
            if (x3.getText().equals(textx)) {
                JOptionPane.showMessageDialog(rootPane, "User 1 is the winner !!");
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "User 2 is the winner !!");
            }
            gamedone();
        }
        else{
            
        }
   
    }
    public void start(){
        x1.setEnabled(true);
        x2.setEnabled(true);
        x3.setEnabled(true);
        x4.setEnabled(true);
        x5.setEnabled(true);
        x6.setEnabled(true);
        x7.setEnabled(true);
        x8.setEnabled(true);
        x9.setEnabled(true);
        start.setEnabled(false);
    }
    public void reset(){
        x1.setText(text);
        x2.setText(text);
        x3.setText(text);
        x4.setText(text);
        x5.setText(text);
        x6.setText(text);
        x7.setText(text);
        x8.setText(text);
        x9.setText(text); 
        reset.setEnabled(false);
        gamedone();
    }
    public void gamedone(){
        x1.setEnabled(false);
        x2.setEnabled(false);
        x3.setEnabled(false);
        x4.setEnabled(false);
        x5.setEnabled(false);
        x6.setEnabled(false);
        x7.setEnabled(false);
        x8.setEnabled(false);
        x9.setEnabled(false);        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton reset;
    private javax.swing.JButton start;
    private javax.swing.JLabel turn;
    private javax.swing.JButton x1;
    private javax.swing.JButton x2;
    private javax.swing.JButton x3;
    private javax.swing.JButton x4;
    private javax.swing.JButton x5;
    private javax.swing.JButton x6;
    private javax.swing.JButton x7;
    private javax.swing.JButton x8;
    private javax.swing.JButton x9;
    // End of variables declaration//GEN-END:variables
}
