/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class uni extends javax.swing.JFrame {

    /**
     * Creates new form uni
     */
    static int grade, year;
    static String course;
    public uni() {
        initComponents();
    }    
    String wronggrade= "There is no such a course for that grade";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TFS Course Taking Panel");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(69, 69, 69));
        jPanel1.setEnabled(false);

        jLabel2.setText("Choose your course");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Our Courses" }));
        jComboBox1.setEnabled(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(69, 69, 69)));
        jPanel2.setEnabled(false);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setText("Course information :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(69, 69, 69)));

        jLabel4.setText("Choose your grade");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Your Grade", "9", "10", "11", "12" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, 0, 140, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setForeground(new java.awt.Color(69, 69, 69));
        jPanel4.setEnabled(false);

        jLabel5.setText("Choose Accademic Year");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("2019/2020");
        jRadioButton1.setEnabled(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("2020/2021");
        jRadioButton2.setEnabled(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addContainerGap())
        );

        jButton2.setText("Start Over");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        if (jComboBox2.getSelectedItem() != "Your Grade") {
            setGrade(Integer.parseInt((String)jComboBox2.getSelectedItem()));
        }
        else{
            jTextArea1.setText("Please choose your grade first !");
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        year = 2019;
        showInformation();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        year = 2020;
        showInformation();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if (jComboBox1.getSelectedItem() == "Our Courses" || jComboBox1.getSelectedItem() == null) {
            jTextArea1.setText("Please choose your course !");
        }
        else{
            setYear((String) jComboBox1.getSelectedItem());
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText(null);
        jComboBox2.setSelectedItem(1);
        jComboBox1.setEnabled(false);
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Our Courses");
        jRadioButton1.setEnabled(false);
        jRadioButton2.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed
    void setYear(String cors){
        jPanel4.setEnabled(true);
        jRadioButton1.setEnabled(true);
        jRadioButton2.setEnabled(true);
        course = cors;
    }
    void setGrade(int grad){
        jPanel1.setEnabled(true);
        jComboBox1.setEnabled(true);
        grade = grad;
        setCourse();
    }
    void setCourse(){
        switch (grade){
                case 9:
                    removeCourses();
                    jComboBox1.addItem("English");
                    jComboBox1.addItem("Mathematics");
                    break;
                case 10:
                    removeCourses();
                    jComboBox1.addItem("English");
                    jComboBox1.addItem("Mathematics");
                    break;
                case 11:
                    removeCourses();
                    jComboBox1.addItem("English");
                    jComboBox1.addItem("Computer Science");
                    jComboBox1.addItem("Mathematics");
                    break;
                case 12:
                    removeCourses();
                    jComboBox1.addItem("English");
                    jComboBox1.addItem("Mathematics");
                    jComboBox1.addItem("Computer Science");
                    break;
                default:
                    break;
        }
    }
    void removeCourses(){
        try {
            jComboBox1.removeAllItems();
            jComboBox1.addItem("Our Courses");
        } catch (Exception e) {
        }
    }
    void showInformation(){
        switch (course) {
            case "Computer Science":
                jTextArea1.setText(ICS());
                break;
            case "Mathematics":
                jTextArea1.setText(Math());
                break;
            case "English":
                jTextArea1.setText(English());
                break;
            default:
                bug();
                break;
                
        }
    }
    String ICS(){
        switch (grade) {
            case 11:
                return "Course name : Introduction to Computer Science \n"+
                "Year :" + year + "/" + (year+1) + "\n"+
                "Grade : " + grade + "\n" +
                "Description : \n" + 
                "This course introduces students to computer science. Students will design software \n"
                + "independently and as part of a team, using industry-standard programming tools and \n"
                + "applying the software development life-cycle model. They will also write and use \n"
                + "subprograms within computer programs. Students will develop creative solutions for \n"
                + "various types of problems as their understanding of the computing environment grows. \n"
                + "They will also explore environmental and ergonomic issues, emerging research in computer \n"
                + "science, and global career trends in computer-related fields.";

            case 12:
                return "Course name : Introduction to Computer Science \n"+
                "Year :" + year + "/" + (year+1) + "\n"+
                "Grade : " + grade + "\n" +
                "Description : \n" +
                "This course introduces students to computer science. Students will design software \n"
                + "independently and as part of a team, using industry-standard programming tools and \n"
                + "applying the software development life-cycle model. They will also write and use \n"
                + "subprograms within computer programs. Students will develop creative solutions for \n"
                + "various types of problems as their understanding of the computing environment grows. \n"
                + "They will also explore environmental and ergonomic issues, emerging research in computer \n"
                + "science, and global career trends in computer-related fields.";

            default:
                return wronggrade;
        }
    }
    String Math(){
        switch (grade) {
            case 9:
                return "Course name :  mathematics  \n"+
                "Year :" + year + "/" + (year+1) + "\n"+
                "Grade : " + grade + "\n" +
                "Description : \n" +
                "This newly developed Math 9 course fully meets the learning outcomes for\n"
                +"the new BC Curriculum. It is the pre-requisite for Foundations of Mathematics \n"
                +"and Pre-Calculus 10, and Workplace Mathematics 10.";

            case 10:
                return "Course name : function \n"+
                "Year :" + year + "/" + (year+1) + "\n"+
                "Grade : " + grade + "\n" +
                "Description : \n" +
                "This course introduces the mathematical concept of the function by extending students' experiences \n"
                +"with linear and quadratic relations. Students will investigate properties of discrete and\n"
                +"continuous functions, including trigonometric and exponential functions; represent functions\n"
                +"numerically, algebraically, and graphically; solve problems involving applications of functions;\n"
                +"investigate inverse functions; and develop facility in determining equivalent algebraic expressions.\n"
                +"Students will reason mathematically and communicate their thinking as they solve multi-step problems.";

            case 11:
                return "Course name : advanced function \n"+
                "Year :" + year + "/" + (year+1) + "\n"+
                "Grade : " + grade + "\n" +
                "Description : \n" +
                "This course extends students’ experience with functions. Students will investigate \n"
                + "the properties of polynomial, rational, logarithmic, and trigonometric functions;\n"
                +"develop techniques for combining functions; broaden their understanding of rates of\n"
                + "change; and develop facility in applying these concepts and skills. Students will also \n"
                + "refine their use of the mathematical processes necessary for success in senior mathematics.\n"
                + " This course is intended both for students taking the Calculus and Vectors course\n"
                + " as a prerequisite for a university program and for those wishing to consolidate their\n"
                + " understanding of mathematics before proceeding to any one of a variety of university\n"
                + " programs.\n" ;

            case 12:
                return "Course name : calculus \n" +
                "Year :" + year + "/" + (year+1) + "\n"+
                "Grade : " + grade + "\n" +
                "Description : \n" +
                "Calculus, originally called infinitesimal calculus or \"the calculus of infinitesimals\",\n"
                + " is the mathematical study of continuous change, in the same way that geometry is \n"
                + "the study of shape and algebra is the study of generalizations of arithmetic operations.";

            default:
                return wronggrade;
        }
    }
    String English(){
        switch (grade) {
            case 9:
                return "Course name :  english as a second language  \n"+
                "Year :" + year + "/" + (year+1) + "\n"+
                "Grade : " + grade + "\n" +
                "Description : \n" +
                "English as a Second Language (ESL), also called English as a Foreign Language (EFL),\n"
                + " is an English language study program for nonnative speakers. Most ESL programs have\n"
                + " small classes so that students receive individual attention from their teachers.";

            case 10:
                return "Course name :  english as a second language  \n"+
                "Year :" + year + "/" + (year+1) + "\n"+
                "Grade : " + grade + "\n" +
                "Description : \n" +
                "English as a Second Language (ESL), also called English as a Foreign Language (EFL),\n"
                + " is an English language study program for nonnative speakers. Most ESL programs have\n"
                + " small classes so that students receive individual attention from their teachers.";

            case 11:
                return "Course name : english  \n"+
                "Year :" + year + "/" + (year+1) + "\n"+
                "Grade : " + grade + "\n" +
                "Description : \n" +
                "english 11 is the course in case to be prepare for uni ";

            case 12:
                return "Course name :  english  \n"+
                "Year :" + year + "/" + (year+1) + "\n"+
                "Grade : " + grade + "\n" +
                "Description : \n" +
                "english 12 is the course in case to be prepare for uni";

            default:
                return wronggrade;
        }
    }
    void bug(){
        jPanel1.setEnabled(false);
        jPanel4.setEnabled(false);
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        jTextArea1.setText(null);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new uni().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
